# Generated by Django 5.1.7 on 2025-05-02 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmsapp', '0002_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
        migrations.AddField(
            model_name='sales',
            name='price_per_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material_price_per_unit', to='scmsapp.material'),
            preserve_default=False,
        ),
    ]
