# Generated by Django 5.1.7 on 2025-05-02 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmsapp', '0003_remove_sales_price_sales_price_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], max_length=10)),
                ('invoice_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scmsapp.customer')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scmsapp.sales')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('invoice_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scmsapp.invoice')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scmsapp.material')),
            ],
        ),
    ]
