# Generated by Django 5.1.7 on 2025-05-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scmsapp', '0004_invoice_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='material',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
