# Generated by Django 5.1.7 on 2025-05-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmsapp', '0005_remove_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
