# Generated by Django 5.1.7 on 2025-05-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scmsapp', '0006_remove_sales_price_per_unit_sales_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='price_per_unit',
            new_name='price',
        ),
    ]
